---
- name: Install keepalived package
  apt: name=keepalived state=present
  sudo: yes

- name: copy keepalived conf
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  sudo: yes
  notify: restart keepalived daemon